spring.application.name=BookMesh

# --- Database  ---
spring.datasource.url=jdbc:mysql://localhost:3306/bookmesh?createDatabaseIfNotExist=true
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- JWT ---
bookmesh.jwt.secret=
bookmesh.jwt.expiration-ms=

logging.level.org.springframework.security=DEBUG


# --- Redis ---
spring,data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis