spring.application.name=BookMesh

# --- Database ---
spring.datasource.url=jdbc:mysql://localhost:3306/bookmesh?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- JWT ---
bookmesh.jwt.secret=a66ce63af71bb552c77bb961ecfb7628c1c60073463b464e1e5bda1c03f3a4bb
bookmesh.jwt.expiration-ms=86400000